#!/bin/sh

trap "rm -r ./tmpjy 2> /dev/null" EXIT

# check input
if [ -f "$1" ]
then
  continue
else
  echo "Invalid file"
  exit 1
fi

min=$(cat "$1" | wc -c)
method=""

# find the best delimiter
list=", | : ; #"
for i in $list
do
  cur=$(abc $i < "$1" | wc -c)
  if [ $min -gt $cur ]
  then
    min=$cur
    method="abc '$i' $1"
  fi
done

# compare the best delimiter with gzip
gzipwc=$(gzip < "$1" | wc -c)
if [ $min -gt $gzipwc ]
then
  min=$gzipwc
  method="gzip $1"
fi

# echo result
echo "$method"

exit 0